In [95]:
import numpy as np

Scrivere una funzione che riceve in ingresso:
* una matrice Nx3 contenene le coordinate di una serie di carica puntiformi (X)
* un vettore di N elementi contenente le rispettive cariche elettriche (Q)
* un vettore di 3 elementi contenente le coordinate di un punto (x)

e resituisce il potenziale elettrostatico nel punto x

In [96]:
def distanza(A, y):
    dis=(np.sqrt(np.sum((A-y)**2, axis=1)))#ricordati sempre di specificare l'asse nella somma quando si tratta di coordinate, devi sommare x con x
    return dis
def potenziale(A, x, y):
    pot=(1/(4*np.pi*(8.854*10**-12)))*np.sum(x/distanza(A,y))
    return pot

Testare la funzione usando i valori di input definiti dal codice sottostante per calcolare il potenziale nell'origine

In [97]:
N = 100
X = np.random.uniform(-10, 10, size = (N, 3))
Q = np.random.normal(loc = 0, scale = 1, size = (N,))

In [98]:
print(distanza(X,np.array([0,0,0])))
a=(distanza(X,np.array([0,0,0])))
print(a.size)
print(potenziale(X,Q,np.array([0,0,0])))

[10.77515845 15.65010737  6.31185193  9.29615379 10.1437235   9.02816599
 10.65647109  9.39899596 13.56841398 11.45257016  3.97155407  3.66741765
 10.10529825  8.54522479  5.98669764 10.57887982 12.38338758 14.14768967
 11.14513066 12.43214097 13.64837307  8.98507197  8.18318868  9.85995166
  5.50172719  8.76676    10.15780931  9.30682879  5.56573754 12.60172829
 12.6267115   7.7681148  12.05797364  7.14874642  9.79619766  7.18288541
 15.78708455 12.57144819  4.99108482 13.18109919 13.54451075  9.28281024
  7.65935389 15.16287644 13.58042781 12.0397577   2.76078508  7.31628143
  9.5239761   8.84757801 12.64209268  4.40823654 10.37638379  8.19662541
 12.0686385  10.43331976 12.86141151 10.03836015  7.80134354 14.06796964
 12.03988391  8.71110191 10.16135468  5.27947334 11.25503796  9.5654782
  6.98965458 10.57756955  6.25837426  6.49798415 10.25938609  8.15022086
 10.78106285 13.40012065 12.44483564  6.90582831  5.81199262  9.70435381
  5.19929509  9.06774041  9.35601965 15.33816721  4.

Scrivere una funzione che riceve in ingresso:

* una matrice Nx3 contenente le coordinate atomiche di una proteina A (crd_A)
* una matrice Mx3 contenente le coordinate atomiche di una proteina B (crd_B)

e restituisce la distanza tra i centri geometrici delle due molecole

In [99]:
def centro_geometrico(C):
    centre=np.sum(C, axis=0)
    centre=centre/C.shape[0]
    return centre

def distanza(A, B):
    dis=np.sqrt(np.sum((A-B)**2))
    return dis

Testare la funzione usando i dati generati dal codice sottostante

In [100]:
import numpy as np
N = 10
M = 20
crd_A = np.random.normal(loc = -0.5, scale = 1.0, size = (N, 3))
crd_B = np.random.normal(loc = 0.5, scale = 1.0, size = (M, 3))

In [101]:
print (crd_A)
print ("il centro geometrico ha come coordinate: ",centro_geometrico(crd_A))
print("la distanza tra i centri geometrici vale:", distanza(centro_geometrico(crd_A), centro_geometrico(crd_B)))

[[ 1.11006694 -2.96049373 -1.11235924]
 [ 0.26305568 -0.24623844 -0.65219967]
 [-1.48094794 -0.44050847 -1.63223213]
 [-1.11806392 -0.84708257 -1.03639272]
 [-0.84780166 -0.05480213  0.54781018]
 [-1.06903905 -0.28549276 -1.39106385]
 [-0.40690667 -0.13373528 -0.6349997 ]
 [-0.69986883 -0.37174469 -0.25344026]
 [-2.37761119 -2.39165387 -1.49190864]
 [-1.11838202  0.05842002  1.0873833 ]]
il centro geometrico ha come coordinate:  [-0.77454987 -0.76733319 -0.65694028]
la distanza tra i centri geometrici vale: 2.046521927090696


Scrivere una funzione che prende in ingresso:

* una matrice Nx3 contenente le coordinate atomiche di una proteina A (crd_A)
* un vettore di N elementi contenente le masse degli atomi della proteina A (m_A)
* una matrice Mx3 contenente le coordinate atomiche di una proteina B (crd_B)
* un vettore di M elementi contenente le masse degli atomi della proteina A (m_A)

e restituisce la distanza tra i centri di massa delle due molecole

In [102]:
'''def centri_massa(crd_A, m_A, crd_B, m_B):
    distanza((sum(crd_A*m_A.reshape(100,-1), axis=1)), (sum(crd_B*m_B.reshape(100,-1), axis=1)))'''
def centro_massa(crd_A, m_A):
    centro=(np.sum(crd_A*m_A.reshape(m_A.shape[0],-1), axis=0)/np.sum(m_A))
    return centro
def distanza(C, D):
    dis=np.sqrt(np.sum((C-D)**2))
    return dis

Testare la funzione usando i dati generati dal codice sottostante

In [103]:
N = 100
M = 200
crd_A = np.random.normal(loc = -0.5, scale = 1.0, size = (N, 3))
m_A = np.random.uniform(1, 10, size = (N,))
crd_B = np.random.normal(loc = 0.5, scale = 1.0, size = (M, 3))
m_B = np.random.uniform(1, 10, size = (M,))

In [104]:
#print(centri_massa(crd_A, m_A, crd_B, m_B))
print(centro_massa(crd_A, m_A))
centro_1=centro_massa(crd_A, m_A)
centro_2=centro_massa(crd_B, m_B)
print(centro_1, centro_2)

print(distanza(centro_massa(crd_A, m_A), centro_massa(crd_B, m_B)))

[-0.39555656 -0.34976653 -0.6567969 ]
[-0.39555656 -0.34976653 -0.6567969 ] [0.48564716 0.54682181 0.56246157]
1.7512800667586657


Scrivere una funzione che prende in ingresso:
* una matrice NxM contenente le coordinate di N punti in uno spazio ad M dimensioni
* un vettore contenente le coordinate di un punto A in uno spazio ad M dimensioni
* un vettore contenente le coordinate di un punto B in uno spazio ad M dimensioni

e restituisce un vettore di N booleani il cui elemento i e' uguale a True se il punto i-esimo della matrice di input e' piu' vicino al punto A che al punto B, False viceversa.

In [105]:
def vicino (A, crd_A, crd_B):
    delta=A-crd_A.reshape(1,-1)
    dist_A=(np.sum(delta**2, axis=1)**0.5)
    delta=A-crd_B.reshape(1,-1)
    dist_b=(np.sum(delta**2, axis=1)**0.5)
    return dist_A>dist_b

Applicare la funzione per calcolare quanti punti della proteina A dell'esercizio sono piu' vicini al centro di massa della proteina B che al centro di massa della proteina A

In [106]:
flag=(vicino(crd_A, centro_2, centro_1))
print(np.sum(flag))

82


Scrivere una funzione che prende in ingresso due matrici 2xN, contenenti le coordinate di una serie di N punti in uno spazio bidimensionale in due diversi istanti di tempo successivi. La funzione deve restituire l'indice del punto che ha subito il maggiore spostamento lungo l'asse x tra i due istanti temporali. [Suggerimento: utilizzare la funzione np.argsort]

Applicare la funzione alle matrici X e Y definite nel codice sottostante. Fare un grafico dei punti che utilizza due simboli diversi per i due istanti temporali, ed un colore diverso per il punto selezionato dalla funzione. Non sono consentiti cicli.

In [107]:
N = 100
X = np.random.normal(size = (2, N))
Y = np.random.normal(size = (2, N))

In [108]:
def spostamento(X,Y):
    delta=np.abs((Y-X))#occhio sempre ai valori assoluti quando prendi delle distanze
    ord=np.argsort(delta[0])
    return ord[-1]
print(spostamento(X,Y))


14


La matrice A definita nel codice sottostante contiene le coordinate di un insiemi di punti organizzati per colonne (la prima colonna di A corrispondende alle coordinate x,y,z di un punto, e cosi via). Scrivere una funzione che prende in ingresso una matrice di punti con la struttura definita per la matrice A e restituisce 3 valori rispettivamente uguali allo spostamento totale lungo gli assi x, y, e z. Per spostamento totale si intende la somma degli spostamenti tra due punti consecutivi.

Esempio. Se la matrice di input e' uguale a:

0 1 2

5 2 4

1 7 2

Il risultato della funzione deve essere: 1+1 (spostamento da 0 a 1 + spostamento da 1 a 2), 3+2 (spostamento da 5 a 2 + spostamento da 2 a 4), 6+5 (spostamento da 1 a 7 + spostamento da 7 a 2)

Applicare la funzione alla matrice A e mostrare a monitor il risultato.

In [109]:
N = 1000
A = np.random.normal(size = (3, N))

In [110]:
def spostamento(A):
    spostamento=(np.sqrt(np.sum(A**2, axis=1)))
    return spostamento
print(spostamento(A))

[31.37014461 31.40824496 31.55069927]
