In [647]:
import numpy as np

Scrivere una funzione che riceve in ingresso:
* una matrice Nx3 contenene le coordinate di una serie di carica puntiformi (X)
* un vettore di N elementi contenente le rispettive cariche elettriche (Q)
* un vettore di 3 elementi contenente le coordinate di un punto (x)

e resituisce il potenziale elettrostatico nel punto x

In [648]:
def distanza(A, y):
    dis=(np.sqrt(np.sum((A-y)**2, axis=1)))#ricordati sempre di specificare l'asse nella somma quando si tratta di coordinate, devi sommare x con x
    return dis
def potenziale(A, x, y):
    pot=(1/(4*np.pi*(8.854*10**-12)))*np.sum(x/distanza(A,y))
    return pot

Testare la funzione usando i valori di input definiti dal codice sottostante per calcolare il potenziale nell'origine

In [649]:
N = 100
X = np.random.uniform(-10, 10, size = (N, 3))
Q = np.random.normal(loc = 0, scale = 1, size = (N,))

In [650]:
print(distanza(X,np.array([0,0,0])))
a=(distanza(X,np.array([0,0,0])))
print(a.size)
print(potenziale(X,Q,np.array([0,0,0])))

[ 6.49921103 11.7658457   3.83215322 14.07828796  3.64987756  9.67403378
  8.34921698  8.51271539  6.5723783   9.98514379  6.49974285 10.00803148
 11.07026276 13.26299894 11.38197586 10.55063258 12.65798672  9.49500264
  9.87215191  8.11526721 11.96402768 13.60974934 11.10731732  8.33575643
  6.93035959 10.02850313  9.87952614  6.16130397  8.56553782 15.10708965
  7.35327939 10.30936857  6.36940647 14.73901766  5.92107484  9.68185569
  8.68703272 10.58636869 10.07901328 10.65024738  8.01259983  7.06482992
  5.98952019 11.85235893 10.22728661  8.84481026 12.55032774 13.60527071
 10.15175939 11.96581675  9.86847736 12.40569565 10.4027501  10.57550139
 11.49228416 12.24735694 12.01038863  8.33796872  4.31579194  7.31300951
 11.16222696  7.49695639  6.19097197 11.5512919   5.7682418  10.04990715
  5.58680471  6.44071746 10.48155008 13.09878304 13.81119128  7.96556688
 10.50949045 12.73198786  8.77345355  8.3898361   8.54692334 11.02214841
  8.90644859  8.72242692  9.09846939  4.53784142 10

Scrivere una funzione che riceve in ingresso:

* una matrice Nx3 contenente le coordinate atomiche di una proteina A (crd_A)
* una matrice Mx3 contenente le coordinate atomiche di una proteina B (crd_B)

e restituisce la distanza tra i centri geometrici delle due molecole

In [651]:
def centro_geometrico(C):
    centre=np.sum(C, axis=0)
    centre=centre/C.shape[0]
    return centre

def distanza(A, B):
    dis=np.sqrt(np.sum((A-B)**2))
    return dis

Testare la funzione usando i dati generati dal codice sottostante

In [652]:
import numpy as np
N = 10
M = 20
crd_A = np.random.normal(loc = -0.5, scale = 1.0, size = (N, 3))
crd_B = np.random.normal(loc = 0.5, scale = 1.0, size = (M, 3))

In [653]:
print (crd_A)
print ("il centro geometrico ha come coordinate: ",centro_geometrico(crd_A))
print("la distanza tra i centri geometrici vale:", distanza(centro_geometrico(crd_A), centro_geometrico(crd_B)))

[[-0.464441   -0.32995256 -0.55938682]
 [-0.66657495 -0.81156212 -0.15642075]
 [-0.07828289 -1.48868767 -0.72170186]
 [-0.12519198  0.72475178 -0.87589074]
 [-1.85194816 -1.17177657  0.4246719 ]
 [ 0.18671267 -1.04513594  0.30074169]
 [ 1.40707112 -1.73852338  1.0288108 ]
 [ 0.85721377 -1.78890868 -0.84716216]
 [ 0.30127556 -1.4756834  -1.26242296]
 [-1.50365632 -0.26190214  0.14480542]]
il centro geometrico ha come coordinate:  [-0.19378222 -0.93873807 -0.25239555]
la distanza tra i centri geometrici vale: 1.7530232030359043


Scrivere una funzione che prende in ingresso:

* una matrice Nx3 contenente le coordinate atomiche di una proteina A (crd_A)
* un vettore di N elementi contenente le masse degli atomi della proteina A (m_A)
* una matrice Mx3 contenente le coordinate atomiche di una proteina B (crd_B)
* un vettore di M elementi contenente le masse degli atomi della proteina A (m_A)

e restituisce la distanza tra i centri di massa delle due molecole

In [654]:
'''def centri_massa(crd_A, m_A, crd_B, m_B):
    distanza((sum(crd_A*m_A.reshape(100,-1), axis=1)), (sum(crd_B*m_B.reshape(100,-1), axis=1)))'''
def centro_massa(crd_A, m_A):
    centro=(np.sum(crd_A*m_A.reshape(m_A.shape[0],-1), axis=0)/np.sum(m_A))
    return centro
def distanza(C, D):
    dis=np.sqrt(np.sum((C-D)**2))
    return dis

Testare la funzione usando i dati generati dal codice sottostante

In [655]:
N = 100
M = 200
crd_A = np.random.normal(loc = -0.5, scale = 1.0, size = (N, 3))
m_A = np.random.uniform(1, 10, size = (N,))
crd_B = np.random.normal(loc = 0.5, scale = 1.0, size = (M, 3))
m_B = np.random.uniform(1, 10, size = (M,))

In [656]:
#print(centri_massa(crd_A, m_A, crd_B, m_B))
print(centro_massa(crd_A, m_A))
centro_1=centro_massa(crd_A, m_A)
centro_2=centro_massa(crd_B, m_B)
print(centro_1, centro_2)

print(distanza(centro_massa(crd_A, m_A), centro_massa(crd_B, m_B)))

[-0.37035083 -0.57991553 -0.65120505]
[-0.37035083 -0.57991553 -0.65120505] [0.38258857 0.54761615 0.48772881]
1.7707105216270482


Scrivere una funzione che prende in ingresso:
* una matrice NxM contenente le coordinate di N punti in uno spazio ad M dimensioni
* un vettore contenente le coordinate di un punto A in uno spazio ad M dimensioni
* un vettore contenente le coordinate di un punto B in uno spazio ad M dimensioni

e restituisce un vettore di N booleani il cui elemento i e' uguale a True se il punto i-esimo della matrice di input e' piu' vicino al punto A che al punto B, False viceversa.

Applicare la funzione per calcolare quanti punti della proteina A dell'esercizio sono piu' vicini al centro di massa della proteina B che al centro di massa della proteina A

Scrivere una funzione che prende in ingresso due matrici 2xN, contenenti le coordinate di una serie di N punti in uno spazio bidimensionale in due diversi istanti di tempo successivi. La funzione deve restituire l'indice del punto che ha subito il maggiore spostamento lungo l'asse x tra i due istanti temporali. [Suggerimento: utilizzare la funzione np.argsort]

Applicare la funzione alle matrici X e Y definite nel codice sottostante. Fare un grafico dei punti che utilizza due simboli diversi per i due istanti temporali, ed un colore diverso per il punto selezionato dalla funzione. Non sono consentiti cicli.

In [657]:
N = 100
X = np.random.normal(size = (2, N))
Y = np.random.normal(size = (2, N))

La matrice A definita nel codice sottostante contiene le coordinate di un insiemi di punti organizzati per colonne (la prima colonna di A corrispondende alle coordinate x,y,z di un punto, e cosi via). Scrivere una funzione che prende in ingresso una matrice di punti con la struttura definita per la matrice A e restituisce 3 valori rispettivamente uguali allo spostamento totale lungo gli assi x, y, e z. Per spostamento totale si intende la somma degli spostamenti tra due punti consecutivi.

Esempio. Se la matrice di input e' uguale a:

0 1 2

5 2 4

1 7 2

Il risultato della funzione deve essere: 1+1 (spostamento da 0 a 1 + spostamento da 1 a 2), 3+2 (spostamento da 5 a 2 + spostamento da 2 a 4), 6+5 (spostamento da 1 a 7 + spostamento da 7 a 2)

Applicare la funzione alla matrice A e mostrare a monitor il risultato.

In [658]:
N = 1000
A = np.random.normal(size = (3, N)

SyntaxError: incomplete input (4157789926.py, line 2)