In [384]:
import numpy as np

Scrivere una funzione che riceve in ingresso:
* una matrice Nx3 contenene le coordinate di una serie di carica puntiformi (X)
* un vettore di N elementi contenente le rispettive cariche elettriche (Q)
* un vettore di 3 elementi contenente le coordinate di un punto (x)

e resituisce il potenziale elettrostatico nel punto x

In [385]:
def distanza(A, y):
    dis=(np.sqrt(np.sum((A-y)**2, axis=1)))#ricordati sempre di specificare l'asse nella somma quando si tratta di coordinate, devi sommare x con x
    return dis
def potenziale(A, x, y):
    pot=(1/(4*np.pi*(8.854*10**-12)))*np.sum(x/distanza(A,y))
    return pot

Testare la funzione usando i valori di input definiti dal codice sottostante per calcolare il potenziale nell'origine

In [386]:
N = 100
X = np.random.uniform(-10, 10, size = (N, 3))
Q = np.random.normal(loc = 0, scale = 1, size = (N,))

In [387]:
print(distanza(X,np.array([0,0,0])))
a=(distanza(X,np.array([0,0,0])))
print(a.size)
print(potenziale(X,Q,np.array([0,0,0])))

[12.70993876 12.1751374   9.86128907  8.38246227 10.65138968 10.01089416
  8.13201355 13.2592606   7.88933071 10.00482565  9.75691798  8.48402697
 12.2964483  11.2117478   9.80852755 13.91937768 10.60846784  9.73141644
  7.14339835 10.33367793 10.43629238 13.57030192 11.34367501 11.66783732
 11.30499346  7.21675446 11.51189424 12.35853989 10.2421059   4.64248951
 11.43873071  6.28567551  8.53224671 11.54866823 11.71575575 12.95452358
 11.78748255 12.38683125 12.5925564  12.21551818  9.20584918  6.07493696
 11.2706053   9.27406609 10.18046438 11.57443427  2.01012921  9.63281998
 14.07477675  7.48341199  7.51182052  7.63294394 11.85301622  8.95703448
  6.85317692  6.07167568  2.53050792  8.84657097 14.4896145   8.07643089
 10.37129765 14.68397211  9.19585588 10.36309082  5.38746864 13.39204497
 12.12509937  9.92891532  9.60766558  8.24494296 12.6032098  14.39447578
  8.26600678  9.49267574 15.15479355  5.70809316  8.77088535  9.0753967
  9.02898559 10.4445856  13.48294878 12.26621777  5.

Scrivere una funzione che riceve in ingresso:

* una matrice Nx3 contenente le coordinate atomiche di una proteina A (crd_A)
* una matrice Mx3 contenente le coordinate atomiche di una proteina B (crd_B)

e restituisce la distanza tra i centri geometrici delle due molecole

In [388]:
def centro_geometrico(C):
    centre=np.sum(C, axis=0)
    centre=centre/C.shape[0]
    return centre

def distanza(A, B):
    dis=np.sqrt(np.sum((A-B)**2))
    return dis

Testare la funzione usando i dati generati dal codice sottostante

In [389]:
import numpy as np
N = 10
M = 20
crd_A = np.random.normal(loc = -0.5, scale = 1.0, size = (N, 3))
crd_B = np.random.normal(loc = 0.5, scale = 1.0, size = (M, 3))

In [390]:
print (crd_A)
print ("il centro geometrico ha come coordinate: ",centro_geometrico(crd_A))
print("la distanza tra i centri geometrici vale:", distanza(centro_geometrico(crd_A), centro_geometrico(crd_B)))

[[-2.47464302 -1.11026337 -0.18566007]
 [-0.63185907 -0.01133767 -0.0446283 ]
 [-0.43762833 -1.12898737 -1.61470384]
 [-0.49106211 -0.16125603  0.4176208 ]
 [ 0.10078293 -1.98250741 -3.24528443]
 [-0.78572549 -0.96864163 -1.69115067]
 [ 0.76093527 -0.54889153 -2.1420521 ]
 [-0.92581878  0.88774198 -1.28131618]
 [-0.36447791 -0.40159676 -1.00968389]
 [ 0.82565313 -0.82891704 -1.0433651 ]]
il centro geometrico ha come coordinate:  [-0.44238434 -0.62546568 -1.18402238]
la distanza tra i centri geometrici vale: 2.313355218843334


Scrivere una funzione che prende in ingresso:

* una matrice Nx3 contenente le coordinate atomiche di una proteina A (crd_A)
* un vettore di N elementi contenente le masse degli atomi della proteina A (m_A)
* una matrice Mx3 contenente le coordinate atomiche di una proteina B (crd_B)
* un vettore di M elementi contenente le masse degli atomi della proteina A (m_A)

e restituisce la distanza tra i centri di massa delle due molecole

In [391]:
'''def centri_massa(crd_A, m_A, crd_B, m_B):
    distanza((sum(crd_A*m_A.reshape(100,-1), axis=1)), (sum(crd_B*m_B.reshape(100,-1), axis=1)))'''
def centro_massa(crd_A, m_A):
    centro=(np.sum(crd_A*m_A.reshape(m_A.shape[0],-1), axis=0)/np.sum(m_A))
    return centro
def distanza(C, D):
    dis=np.sqrt(np.sum((C-D)**2))
    return dis

Testare la funzione usando i dati generati dal codice sottostante

In [392]:
N = 100
M = 200
crd_A = np.random.normal(loc = -0.5, scale = 1.0, size = (N, 3))
m_A = np.random.uniform(1, 10, size = (N,))
crd_B = np.random.normal(loc = 0.5, scale = 1.0, size = (M, 3))
m_B = np.random.uniform(1, 10, size = (M,))

In [393]:
#print(centri_massa(crd_A, m_A, crd_B, m_B))
print(centro_massa(crd_A, m_A))
centro_1=centro_massa(crd_A, m_A)
centro_2=centro_massa(crd_B, m_B)
print(centro_1, centro_2)

print(distanza(centro_massa(crd_A, m_A), centro_massa(crd_B, m_B)))

[-0.41974585 -0.31002771 -0.45554815]
[-0.41974585 -0.31002771 -0.45554815] [0.51490476 0.53123508 0.476074  ]
1.5649967046478854


Scrivere una funzione che prende in ingresso:
* una matrice NxM contenente le coordinate di N punti in uno spazio ad M dimensioni
* un vettore contenente le coordinate di un punto A in uno spazio ad M dimensioni
* un vettore contenente le coordinate di un punto B in uno spazio ad M dimensioni

e restituisce un vettore di N booleani il cui elemento i e' uguale a True se il punto i-esimo della matrice di input e' piu' vicino al punto A che al punto B, False viceversa.

In [394]:
def vicino (A, crd_A, crd_B):
    delta=A-crd_A.reshape(1,-1)
    dist_A=(np.sum(delta**2, axis=1)**0.5)
    delta=A-crd_B.reshape(1,-1)
    dist_b=(np.sum(delta**2, axis=1)**0.5)
    return dist_A>dist_b

Applicare la funzione per calcolare quanti punti della proteina A dell'esercizio sono piu' vicini al centro di massa della proteina B che al centro di massa della proteina A

In [395]:
flag=(vicino(crd_A, centro_2, centro_1))
print(np.sum(flag))

78


Scrivere una funzione che prende in ingresso due matrici 2xN, contenenti le coordinate di una serie di N punti in uno spazio bidimensionale in due diversi istanti di tempo successivi. La funzione deve restituire l'indice del punto che ha subito il maggiore spostamento lungo l'asse x tra i due istanti temporali. [Suggerimento: utilizzare la funzione np.argsort]

Applicare la funzione alle matrici X e Y definite nel codice sottostante. Fare un grafico dei punti che utilizza due simboli diversi per i due istanti temporali, ed un colore diverso per il punto selezionato dalla funzione. Non sono consentiti cicli.

In [396]:
N = 100
X = np.random.normal(size = (2, N))
Y = np.random.normal(size = (2, N))

In [ ]:
def spostamento(X,Y):
    np.abs(delta=(Y-X))#occhio sempre ai valori assoluti quando prendi delle distanze
    ord=np.argsort(delta[0])
    return ord[-1]
print(spostamento(X,Y))


5


La matrice A definita nel codice sottostante contiene le coordinate di un insiemi di punti organizzati per colonne (la prima colonna di A corrispondende alle coordinate x,y,z di un punto, e cosi via). Scrivere una funzione che prende in ingresso una matrice di punti con la struttura definita per la matrice A e restituisce 3 valori rispettivamente uguali allo spostamento totale lungo gli assi x, y, e z. Per spostamento totale si intende la somma degli spostamenti tra due punti consecutivi.

Esempio. Se la matrice di input e' uguale a:

0 1 2

5 2 4

1 7 2

Il risultato della funzione deve essere: 1+1 (spostamento da 0 a 1 + spostamento da 1 a 2), 3+2 (spostamento da 5 a 2 + spostamento da 2 a 4), 6+5 (spostamento da 1 a 7 + spostamento da 7 a 2)

Applicare la funzione alla matrice A e mostrare a monitor il risultato.

In [398]:
N = 1000
A = np.random.normal(size = (3, N)

SyntaxError: incomplete input (4157789926.py, line 2)