Importare la libreria numpy

In [183]:
import numpy as np

Definire manualmente un vettore monodimensionale di 10 valori interi

Scrivere le istruzioni per stampare:
* il numero di elementi del vettore
* il numero di dimensioni del vettore
* la shape del vettore
* il terzo elemento
* il penultimo elemento

In [184]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
print(x.size, x.ndim, x.shape, x[2], x[-2])

10 1 (10,) 3 9


Definire manualmente un vettore bi-dimensionale di 4 righe e 3 colonne di numeri interi

Scrivere le istruzioni per stampare:
* il numero di elementi del vettore
* il numero di dimensioni del vettore
* la shape del vettore
* il numero di righe
* il numero di colonne
* l'elemento sulla seconda riga, prima colonna
* la seconda riga
* la prima colonna

In [185]:
x=np.array([[1,2,3], [1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(x.size, x.ndim, x.shape, x.shape[0], x.shape[1], x[1,0], x[1,:], x[:,0])

12 2 (4, 3) 4 3 1 [1 2 3] [1 1 1 1]


* Definire un vettore x contenente i numeri interi da 0 a 20 (incluso) utilizzando la funzione np.arange
* Definire un vettore y contenente 21 numeri equidistanti tra 0 e 1000
* Calcolare un vettore z i cui elementi sono uguali a x\*\*2 + y

In [186]:
x=np.arange(21)
y=np.linspace(0, 1000, 21)
z=x**2+y
print(x, y, z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [   0.   50.  100.  150.  200.  250.  300.  350.  400.  450.  500.  550.
  600.  650.  700.  750.  800.  850.  900.  950. 1000.] [   0.   51.  104.  159.  216.  275.  336.  399.  464.  531.  600.  671.
  744.  819.  896.  975. 1056. 1139. 1224. 1311. 1400.]


* Calcolare un vettore z che contiene tutte le differenze tra i valori consecutivi di y

In [187]:
z=((y[1:])-y[:-1])
print(z)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50. 50. 50. 50. 50. 50. 50. 50. 50.
 50. 50.]


* definire una matrice che ha come righe i vettori x e y definiti in precedenza
* definire una matrice che ha come colonne i vettori x e y definiti in precedenza

In [188]:
a=np.concatenate((x.reshape((1,-1)), y.reshape((1, -1))), axis=0)
a
a=np.concatenate((x.reshape((-1,1)), y.reshape((-1, 1)) ), axis=1)
a

array([[   0.,    0.],
       [   1.,   50.],
       [   2.,  100.],
       [   3.,  150.],
       [   4.,  200.],
       [   5.,  250.],
       [   6.,  300.],
       [   7.,  350.],
       [   8.,  400.],
       [   9.,  450.],
       [  10.,  500.],
       [  11.,  550.],
       [  12.,  600.],
       [  13.,  650.],
       [  14.,  700.],
       [  15.,  750.],
       [  16.,  800.],
       [  17.,  850.],
       [  18.,  900.],
       [  19.,  950.],
       [  20., 1000.]])

* Definire una matrice 4x20 le cui prime due righe sono costiuite da 0, la terza riga dai numeri interi tra 0 e 19, e la quarta riga dai numeri interi da 19 a 0

In [189]:
a=np.array([np.zeros(20), np.zeros(20), np.arange(20), np.arange(19, -1, -1)])
a
#è impertante definire solo vettori dimensionali e non vettori riga altrimenti non hanno la stessa shape dei vettori monodimensionali creati con
#arange. le parentesi quadre non servono se nella definizione della matrice sto definendo dei vettori.

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [19., 18., 17., 16., 15., 14., 13., 12., 11., 10.,  9.,  8.,  7.,
         6.,  5.,  4.,  3.,  2.,  1.,  0.]])

In [190]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

* Dati i due vettori x e y definiti nel codice sottostante calcolare:
    * il prodotto scalare
    * la norma dei due vettori

In [191]:
x = np.random.randint(low = 0, high = 100, size = 10)
y = np.random.randint(low = 0, high = 100, size = 10)

In [192]:
prodotto_scalare=np.sum(x*y)#riguardati il metodo sum
print(prodotto_scalare)
prodotto_scalare_2=np.dot(x,y)#funzione prosotto scalare
print(prodotto_scalare_2)
norma=np.sqrt(np.sum(x**2))
print(norma)
norma_2=np.linalg.norm((x))
print(norma_2)


21821
21821
155.52170266557656
155.52170266557656


* Utilizzando gli stessi vettore x e y del punto precedente calcolare la matrice 10 x 10 contenente nella posizione i, j il valore assoluto della differenza tra x\[i\] e y\[j\]

In [193]:
print(x)
print(y)
a=np.abs(x.reshape(1,-1)-y.reshape(-1,1))
print(a)

[38 56  2 12 17 19 90 32 73 66]
[68 28 68 17 83 62 80 92  6 63]
[[30 12 66 56 51 49 22 36  5  2]
 [10 28 26 16 11  9 62  4 45 38]
 [30 12 66 56 51 49 22 36  5  2]
 [21 39 15  5  0  2 73 15 56 49]
 [45 27 81 71 66 64  7 51 10 17]
 [24  6 60 50 45 43 28 30 11  4]
 [42 24 78 68 63 61 10 48  7 14]
 [54 36 90 80 75 73  2 60 19 26]
 [32 50  4  6 11 13 84 26 67 60]
 [25  7 61 51 46 44 27 31 10  3]]


* Contare il numero di elementi positivi nelle ultime due colonne della matrice A

In [194]:
A = np.random.randint(low = -10, high = 11, size = (5,4))

In [195]:
count=0
print(A[:,-2:])
count=np.sum(A[:,-2:]>0, axis=1)#anche alla sum posso dare un asse per dire come socorrere contare gli elementi
count


[[ -7   6]
 [  6  -8]
 [ -9   7]
 [  8 -10]
 [ -8   2]]


array([1, 1, 1, 1, 1])