In [115]:
import numpy as np

Scrivere una funzione che riceve in ingresso:
* una matrice Nx3 contenene le coordinate di una serie di carica puntiformi (X)
* un vettore di N elementi contenente le rispettive cariche elettriche (Q)
* un vettore di 3 elementi contenente le coordinate di un punto (x)

e resituisce il potenziale elettrostatico nel punto x

In [116]:
def distanza(A, y):
    dis=(np.sqrt(np.sum((A-y)**2, axis=1)))#ricordati sempre di specificare l'asse nella somma quando si tratta di coordinate, devi sommare x con x
    return dis
def potenziale(A, x, y):
    pot=(1/(4*np.pi*(8.854*10**-12)))*np.sum(x/distanza(A,y))
    return pot

Testare la funzione usando i valori di input definiti dal codice sottostante per calcolare il potenziale nell'origine

In [117]:
N = 100
X = np.random.uniform(-10, 10, size = (N, 3))
Q = np.random.normal(loc = 0, scale = 1, size = (N,))

In [118]:
print(distanza(X,np.array([0,0,0])))
a=(distanza(X,np.array([0,0,0])))
print(a.size)
print(potenziale(X,Q,np.array([0,0,0])))

[12.42493025 11.02328564 10.32078806  8.79086618  4.17543581  9.66861706
 11.22116823 15.81455777  9.56840674 13.25466413  5.52860787 10.09490778
 14.91355967 10.73558601  6.88508458 10.62488429 12.29751038 13.26194197
 11.92137336  4.73148304  8.77181115 13.95828838 11.39651321 10.74438331
 12.0269547   6.95288394  4.97204868  7.53960479  9.76039021 11.40958385
  7.69461978  9.07831864  9.58952707  7.88405757 10.87332922  5.97175751
 12.75894897  6.19927309  9.28755072  9.70335956  9.22015553  9.63009692
  6.68964882 11.28176714  8.77053968  3.74753377 10.2824886   8.51697776
 11.56484021  9.9256214   2.85766338  9.44447559  8.58000105 10.18999741
 11.05637981  8.46376453 10.15334646  9.44797842 11.70792329 13.97425128
  6.4083657  12.1899674  10.78398828 12.09468575 10.82682263 10.84452477
 10.93019971  5.89176531 10.73596059  6.04780469 10.24255272  8.41996103
  6.60171178  9.41062393  8.07180597  6.91538661 10.26664056  9.17356438
 10.55400096 11.30531279 14.54884627 10.68205793  9

Scrivere una funzione che riceve in ingresso:

* una matrice Nx3 contenente le coordinate atomiche di una proteina A (crd_A)
* una matrice Mx3 contenente le coordinate atomiche di una proteina B (crd_B)

e restituisce la distanza tra i centri geometrici delle due molecole

In [119]:
def centro_geometrico(C):
    centre=np.sum(C, axis=0)
    centre=centre/C.shape[0]
    return centre

def distanza(A, B):
    dis=np.sqrt(np.sum((A-B)**2))
    return dis

Testare la funzione usando i dati generati dal codice sottostante

In [120]:
import numpy as np
N = 10
M = 20
crd_A = np.random.normal(loc = -0.5, scale = 1.0, size = (N, 3))
crd_B = np.random.normal(loc = 0.5, scale = 1.0, size = (M, 3))

In [121]:
print (crd_A)
print ("il centro geometrico ha come coordinate: ",centro_geometrico(crd_A))
print("la distanza tra i centri geometrici vale:", distanza(centro_geometrico(crd_A), centro_geometrico(crd_B)))

[[-1.04862253  0.89168259 -1.30541475]
 [-1.86090808  0.20104807 -0.69257465]
 [-1.81686638 -1.89797506 -2.62687325]
 [ 0.52686897 -0.41336726 -0.93999024]
 [-1.121304   -2.38680024  1.10055157]
 [-0.98182127 -1.11806829 -0.15514139]
 [-1.13590494 -0.40614916 -0.092697  ]
 [-1.61687681 -2.74764238 -0.66192253]
 [-0.03707731  0.34595942 -2.21334973]
 [ 0.79906643 -0.61564573 -0.75978465]]
il centro geometrico ha come coordinate:  [-0.82934459 -0.8146958  -0.83471966]
la distanza tra i centri geometrici vale: 2.787133811512513


Scrivere una funzione che prende in ingresso:

* una matrice Nx3 contenente le coordinate atomiche di una proteina A (crd_A)
* un vettore di N elementi contenente le masse degli atomi della proteina A (m_A)
* una matrice Mx3 contenente le coordinate atomiche di una proteina B (crd_B)
* un vettore di M elementi contenente le masse degli atomi della proteina A (m_A)

e restituisce la distanza tra i centri di massa delle due molecole

In [122]:
'''def centri_massa(crd_A, m_A, crd_B, m_B):
    distanza((sum(crd_A*m_A.reshape(100,-1), axis=1)), (sum(crd_B*m_B.reshape(100,-1), axis=1)))'''
def centro_massa(crd_A, m_A):
    centro=(np.sum(crd_A*m_A.reshape(m_A.shape[0],-1), axis=0)/np.sum(m_A))
    return centro
def distanza(C, D):
    dis=np.sqrt(np.sum((C-D)**2))
    return dis

Testare la funzione usando i dati generati dal codice sottostante

In [123]:
N = 100
M = 200
crd_A = np.random.normal(loc = -0.5, scale = 1.0, size = (N, 3))
m_A = np.random.uniform(1, 10, size = (N,))
crd_B = np.random.normal(loc = 0.5, scale = 1.0, size = (M, 3))
m_B = np.random.uniform(1, 10, size = (M,))

In [124]:
#print(centri_massa(crd_A, m_A, crd_B, m_B))
print(centro_massa(crd_A, m_A))
centro_1=centro_massa(crd_A, m_A)
centro_2=centro_massa(crd_B, m_B)
print(centro_1, centro_2)

print(distanza(centro_massa(crd_A, m_A), centro_massa(crd_B, m_B)))

[-0.64206566 -0.49231504 -0.28968491]
[-0.64206566 -0.49231504 -0.28968491] [0.51885403 0.56180949 0.37064713]
1.7014556895131412


Scrivere una funzione che prende in ingresso:
* una matrice NxM contenente le coordinate di N punti in uno spazio ad M dimensioni
* un vettore contenente le coordinate di un punto A in uno spazio ad M dimensioni
* un vettore contenente le coordinate di un punto B in uno spazio ad M dimensioni

e restituisce un vettore di N booleani il cui elemento i e' uguale a True se il punto i-esimo della matrice di input e' piu' vicino al punto A che al punto B, False viceversa.

In [125]:
def vicino (A, crd_A, crd_B):
    delta=A-crd_A.reshape(1,-1)
    dist_A=(np.sum(delta**2, axis=1)**0.5)
    delta=A-crd_B.reshape(1,-1)
    dist_b=(np.sum(delta**2, axis=1)**0.5)
    return dist_A>dist_b

Applicare la funzione per calcolare quanti punti della proteina A dell'esercizio sono piu' vicini al centro di massa della proteina B che al centro di massa della proteina A

In [126]:
flag=(vicino(crd_A, centro_2, centro_1))
print(np.sum(flag))

83


Scrivere una funzione che prende in ingresso due matrici 2xN, contenenti le coordinate di una serie di N punti in uno spazio bidimensionale in due diversi istanti di tempo successivi. La funzione deve restituire l'indice del punto che ha subito il maggiore spostamento lungo l'asse x tra i due istanti temporali. [Suggerimento: utilizzare la funzione np.argsort]

Applicare la funzione alle matrici X e Y definite nel codice sottostante. Fare un grafico dei punti che utilizza due simboli diversi per i due istanti temporali, ed un colore diverso per il punto selezionato dalla funzione. Non sono consentiti cicli.

In [127]:
N = 100
X = np.random.normal(size = (2, N))
Y = np.random.normal(size = (2, N))

In [ ]:
def spostamento(X,Y):
    tempo_1_max=np.argsort(M[-1,0])
    tempo_2_max

La matrice A definita nel codice sottostante contiene le coordinate di un insiemi di punti organizzati per colonne (la prima colonna di A corrispondende alle coordinate x,y,z di un punto, e cosi via). Scrivere una funzione che prende in ingresso una matrice di punti con la struttura definita per la matrice A e restituisce 3 valori rispettivamente uguali allo spostamento totale lungo gli assi x, y, e z. Per spostamento totale si intende la somma degli spostamenti tra due punti consecutivi.

Esempio. Se la matrice di input e' uguale a:

0 1 2

5 2 4

1 7 2

Il risultato della funzione deve essere: 1+1 (spostamento da 0 a 1 + spostamento da 1 a 2), 3+2 (spostamento da 5 a 2 + spostamento da 2 a 4), 6+5 (spostamento da 1 a 7 + spostamento da 7 a 2)

Applicare la funzione alla matrice A e mostrare a monitor il risultato.

In [128]:
N = 1000
A = np.random.normal(size = (3, N)

SyntaxError: incomplete input (4157789926.py, line 2)