Importare la libreria numpy

In [2]:
import numpy as np

Definire manualmente un vettore monodimensionale di 10 valori interi

Scrivere le istruzioni per stampare:
* il numero di elementi del vettore
* il numero di dimensioni del vettore
* la shape del vettore
* il terzo elemento
* il penultimo elemento

In [3]:
x = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

print(len(x))
print(x.ndim)
print(x.shape)
print(x[2])
print(x[-2])

10
1
(10,)
7
1


Definire manualmente un vettore bi-dimensionale di 4 righe e 3 colonne di numeri interi

Scrivere le istruzioni per stampare:
* il numero di elementi del vettore
* il numero di dimensioni del vettore
* la shape del vettore
* il numero di righe
* il numero di colonne
* l'elemento sulla seconda riga, prima colonna
* la seconda riga
* la prima colonna

In [4]:
A = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8],
    [9,10,11],
])

print(len(A))
print(A.ndim)
print(A.shape)
print(A.shape[0])
print(A.shape[1])
print(A[1,0])
print(A[1,:])
print(A[:,0])

4
2
(4, 3)
4
3
3
[3 4 5]
[0 3 6 9]


* Definire un vettore x contenente i numeri interi da 0 a 20 (incluso) utilizzando la funzione np.arange
* Definire un vettore y contenente 21 numeri equidistanti tra 0 e 1000 utilizzando la funzione np.linspace
* Calcolare un vettore z i cui elementi sono uguali a x\*\*2 + y

In [5]:
x = np.arange(0,21)
y = np.linspace(0,1000,21)
z = x**2 + y
print(z)

[   0.   51.  104.  159.  216.  275.  336.  399.  464.  531.  600.  671.
  744.  819.  896.  975. 1056. 1139. 1224. 1311. 1400.]


* Calcolare un vettore z che contiene tutte le differenze tra i valori consecutivi di y (z\[i\] = y\[i+1\] - y\[i\])

In [6]:
# soluzione con ciclo --> pessima implementazione
z = np.zeros(len(x)-1)
for i in range(len(z)):
    z[i] = y[i+1] - y[i]

In [7]:
# soluzione senza ciclo --> piu' efficient
z = y[1:] - y[:-1]

* definire una matrice che ha come righe i vettori x e y definiti in precedenza
* definire una matrice che ha come colonne i vettori x e y definiti in precedenza

In [8]:
A = np.concatenate((x.reshape((1,-1)), y.reshape((1,-1))), axis = 0)
print(A)

[[   0.    1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.
    12.   13.   14.   15.   16.   17.   18.   19.   20.]
 [   0.   50.  100.  150.  200.  250.  300.  350.  400.  450.  500.  550.
   600.  650.  700.  750.  800.  850.  900.  950. 1000.]]


In [9]:
B = np.concatenate((x.reshape((-1,1)), y.reshape((-1,1))), axis = 1)
print(B)

[[   0.    0.]
 [   1.   50.]
 [   2.  100.]
 [   3.  150.]
 [   4.  200.]
 [   5.  250.]
 [   6.  300.]
 [   7.  350.]
 [   8.  400.]
 [   9.  450.]
 [  10.  500.]
 [  11.  550.]
 [  12.  600.]
 [  13.  650.]
 [  14.  700.]
 [  15.  750.]
 [  16.  800.]
 [  17.  850.]
 [  18.  900.]
 [  19.  950.]
 [  20. 1000.]]


* Definire una matrice 20 x 4 le cui prime due righe sono costiuite da 0, la terza riga dai numeri interi tra 0 e 19, e la quarta riga dai numeri interi da 19 a 0

In [10]:
r_1_2 = np.zeros(20)
r3 = np.arange(0,20)
r4 = np.arange(19,-1,-1)
C = np.concatenate((r_1_2.reshape((1,-1)), r_1_2.reshape((1,-1)), r3.reshape((1,-1)), r4.reshape((1,-1))), axis = 0)
print(C)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19.]
 [19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.  4.  3.  2.
   1.  0.]]


* Dati i due vettore x e y definiti nel codice sottostante calcolare:
    * il prodotto scalare
    * la norma dei due vettori

In [11]:
x = np.random.randint(low = 0, high = 100, size = 10)
y = np.random.randint(low = 0, high = 100, size = 10)

In [12]:
print(np.sum(x*y))
print(np.sqrt(np.sum(x*x)))
print(np.sqrt(np.sum(y*y)))

23956
135.39202339872168
215.20223047171234


* Utilizzando gli stessi vettore x e y del punto precedente calcolare la matrice 10 x 10 contenente nella posizione i, j il valore assoluto della differenza tra x\[i\] e y\[j\]
* Suggerimento: la funzione np.abs calcola il valore assoluto

In [13]:
# soluzione formalmente corretta ma inefficiente
A = np.zeros((len(x), len(y)))
for i in range(len(x)):
    for j in range(len(y)):
        A[i,j] = np.abs(x[i] - y[j])

In [14]:
# soluzione senza cicli --> piu' efficiente
A = np.abs(x.reshape((1,-1)) - y.reshape((-1,1)))

* Data la matrice A definita nel codice sottostante, scrivere le istruzioni per stampare gli elementi della seconda colonna di A solo per le righe in cui la prima colonna contiene valori positivi

In [15]:
A = np.random.randint(low = -10, high = 11, size = (5,4))
print(A)

[[ -7  -5 -10  -6]
 [  7  10  -1   8]
 [  5   7   3   6]
 [  1   4  -6  -5]
 [  3   4   4  10]]


In [16]:
# soluzione formalmente corretta ma inefficiente
for i in range(A.shape[0]):
    if A[i,0] > 0:
        print(A[i,1])

10
7
4
4


In [17]:
print(A[A[:,0]>0,1]) # soluzione corretta

[10  7  4  4]


* Contare il numero di elementi positivi nelle ultime due colonne della matrice A

In [18]:
# soluzione formalmente corretta ma inefficiente
n = 0
for j in [-1, -2]:
    for i in range(A.shape[0]):
        if A[i,j] > 0:
            n += 1

In [19]:
n = np.sum(A[:,[-2,-1]] > 0) # soluzione corretta