In [66]:
import numpy as np

In [67]:
x=np.array([1, 2, 6, 9, -1])

In [68]:
x[[1, 3, 1, 0]]

array([2, 9, 2, 1])

In [69]:
np.argsort(x)

array([4, 0, 1, 2, 3])

In [70]:
x[np.argsort(x)]

array([-1,  1,  2,  6,  9])

In [71]:
A=np.array([[1,2,3], [4,5,6], [7,8,9]])

In [72]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
A[[0,0,1], :]

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
A=np.random.randint(low=0, high=10, size=(10,4))
A

array([[9, 7, 2, 3],
       [4, 4, 0, 4],
       [1, 0, 1, 6],
       [9, 8, 2, 4],
       [1, 0, 0, 9],
       [3, 8, 3, 2],
       [8, 8, 9, 4],
       [0, 9, 2, 5],
       [5, 9, 0, 6],
       [5, 1, 2, 6]])

In [75]:
A[np.argsort(A[:,1]),:]

array([[1, 0, 1, 6],
       [1, 0, 0, 9],
       [5, 1, 2, 6],
       [4, 4, 0, 4],
       [9, 7, 2, 3],
       [9, 8, 2, 4],
       [3, 8, 3, 2],
       [8, 8, 9, 4],
       [0, 9, 2, 5],
       [5, 9, 0, 6]])

In [76]:
A[A[:,1]>4, :]

array([[9, 7, 2, 3],
       [9, 8, 2, 4],
       [3, 8, 3, 2],
       [8, 8, 9, 4],
       [0, 9, 2, 5],
       [5, 9, 0, 6]])