In [ ]:
#parleremo di efficienze di un codice

In [3]:
def f():
    for i in range (1000):
        k=i**2.0

In [4]:
import time
ts=time.time() #restituisce un oggetto che rappresenta l'istante temporale in cui è stata chiamata la finzione
f()
te=time.time()

In [ ]:
print (te-ts) #restituisce la differenza in secondi quanto ha impiegato la funzione, visto che ts viene assegnato prima di chiamarla e te dopo

0.00019788742065429688


In [ ]:
%timeit f() #è un'istruzione non di python ma del jupiter notebook, 
#esegue un certo numero di volte la funzione, in questo caso 7, e calcola il tempo medio di esecuzione, è molto più preciso
#quando uso, come prima, ts e te, è possibile che tra ts e te potrebbero essere eseguite altre cose x, quindi conviene usare sempre %time.it

50 μs ± 1.37 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
#iniziamo a lavorare con numpy

In [9]:
import numpy as np
'''il primo oggetto che vediamo è il vettore numpy, elemento base della libreria numpy
il vettore numpy è multidimensionale, al contrario della lista che è monodimensionale
è fatto di un solo tipo di elementi, al contrario della lista che poteva avere elementi di tipo diverso
il tipo intero di un vettore numpy sono degli interi con un range (8 bit, 16,32,64) quando definiamo un vettore bisogna specificare il tipo di dato
ad esempio tra interi e float e il tipo di interi o float
il vettore può essere di interi, float, bool, e numeri complessi, noi useremo quasi solo int e float con le impostazioni predefinite dell'interprete'''



"il primo oggetto che vediamo è il vettore numpy, elemento base della libreria numpy\nil vettore numpy è multidimensionale, al contrario della lista che è monodimensionale\nè fatto di un solo tipo di elementi, al contrario della lista che poteva avere elementi di tipo diverso\nil tipo intero di un vettore numpy sono degli interi con un range (8 bit, 16,32,64) quando definiamo un vettore bisogna specificare il tipo di dato\nad esempio tra interi e float e il tipo di interi o float\nil vettore può essere di interi, float, bool, e numeri complessi, noi useremo quasi solo int e float con le impostazioni predefinite dell'interprete"

In [ ]:
x=np.array([1, 3, 7, 8, -1]) #abbiamo definito un vettore multidimensionale di interi

In [11]:
print(x)

[ 1  3  7  8 -1]


In [12]:
type (x)

numpy.ndarray

In [ ]:
x[2]#esattamente come nelle liste possiamo pescare gli elementi indicizzati
x[:3]#valgono tutte le regole di indicizzazione e slicing

array([1, 3, 7])

In [ ]:
len (x)#anche len() funziona come nelle liste

5

In [16]:
x.ndim #sto pescando l'attributo ndim di ix, un attributo è una caratteristica dell'oggetto, in questo caso ndim è il numero di dimensioni

1

In [ ]:
x.shape #è la forma del vettore se fosse stato un vettore di più dimensioni avrebbe stampato il numero di elementi lungo le altre dimensioni

(5,)

In [18]:
x.size #ci dice quanto è grande il vettore, se fosse stata una matrice 5x2 avrebbe scritto 10

5

In [ ]:
x.dtype #ci dice di che tipo sono gli elementi del vettore, in questo caso interi a 64 bit

dtype('int64')

In [24]:
x=np.array([-1, 3, 4, 5, -1.0])
x.dtype#in questo caso tutti gli elementi vengono considerati float, non come nelle liste dove solo uno sarebbe stato float e gli altri int

dtype('float64')

In [26]:
x.itemsize #mi dice quanti byte occupa ciascun elemento del vettore



8

In [27]:
x.nbytes#ci dice il numero di bytes che occupa l'intero vettore

40

In [31]:
A=np.array([[0, 2, 5], [3, 4, 7], [1, 0, -1], [-9, 4, 2]])
#è un vettore numpy ndimensionale in questo caso di 2 dimensioni, la lista interna definisce le righe
            

In [33]:
A.ndim

2

In [34]:
A.shape

(4, 3)

In [ ]:
A=np.array([[[0, 2, 5], [3, 4, 7], [1, 0, -1], [-9, 4, 2]], [[0, 2, 5], [3, 4, 7], [1, 0, -1], [-9, 4, 2]]])
#questa è una matrice di 3 dimensioni

In [37]:
print (A)

[[[ 0  2  5]
  [ 3  4  7]
  [ 1  0 -1]
  [-9  4  2]]

 [[ 0  2  5]
  [ 3  4  7]
  [ 1  0 -1]
  [-9  4  2]]]


In [40]:
A.ndim

3

In [41]:
A.shape


(2, 4, 3)

In [42]:
A=np.array([[0, 2, 5], [3, 4, 7], [1, 0, -1], [-9, 4, 2]])

In [43]:
print (A)

[[ 0  2  5]
 [ 3  4  7]
 [ 1  0 -1]
 [-9  4  2]]


In [44]:
A[2,0]#prendo l'elemendo della terza riga, prima colonna

1

In [47]:
for ir in range(A.shape[0]):#A.shape mi restituisce la tupla della quale le righe sono l'elemento di indice 0
    for ic in range(A.shape[1]):#A.shape mi restituisce la tupla della quale le colonne sono l'elemento di indice 1
        print (A[ir, ic])

0
2
5
3
4
7
1
0
-1
-9
4
2


In [ ]:
A[0:2,2]#stesso slicing delle liste, in questo caso prendo le prime due righe e la terza colonna

array([5, 7])

In [49]:
A[1:, 2] #parto dalla seconda riga, arrivo all'ultima e prendo la terza colonna

array([ 7, -1,  2])

In [ ]:
A[::-1,0]#prendo la prima colonna ma letta al contrario

array([-9,  1,  3,  0])

In [ ]:
A[::-1, 0:2] #posso eseguire lo slicing in tutte le dimensioni

array([[-9,  4],
       [ 1,  0],
       [ 3,  4],
       [ 0,  2]])

In [ ]:
A[::-1, :]#prendo tutta la matrice facendo una riflessione verticale

array([[-9,  4,  2],
       [ 1,  0, -1],
       [ 3,  4,  7],
       [ 0,  2,  5]])

In [ ]:
x=np.ones(10)#costruisce di default un vettore di float pariu a 1.

In [ ]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
x=np.ones (10, dtype=np.int8)#posso in questo modo specificare il tipo di dato da inserire e quanti elementi inserire

In [60]:
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
x[0]=32000#dà errore in quanto avevo scelto interi di soli 8 bit che non bastano per rappresentare 32000

/var/folders/zk/_8kgcnss2970p4t4pl1k17gm0000gn/T/ipykernel_15114/1451188793.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 32000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  x[0]=32000


In [ ]:
x=np.ones((4,8), dtype=np.int64)#definisco una matrice 4x8 di uni

In [63]:
x

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
x=np.zeros((4,8))#definisco una matrice 4x8 di zeri, anche in questo caso, di default saranno float

In [65]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
I=np.eye(10)#eye è il modo per definire la matrice identità

In [67]:
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
x=np.arange(10)#in questo caso dando solo 10 dico alla arange dove arrivare, ovviamente come sempre in python si ferma a 9 non a 10

In [70]:
10

10

In [71]:
x=np.arange(-1,13)

In [72]:
x

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
x=np.arange(-4, 4, 0.25)#in questo caso gli dico da dove part a dove arrivo e on che periodo mi muovo

In [75]:
x

array([-4.  , -3.75, -3.5 , -3.25, -3.  , -2.75, -2.5 , -2.25, -2.  ,
       -1.75, -1.5 , -1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,
        0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,
        2.75,  3.  ,  3.25,  3.5 ,  3.75])

In [77]:
np.pi

3.141592653589793

In [78]:
np.arange(-np.pi, np.pi, np.pi/10) #sto prendendo i valori da meno pi greco a pi greco con uno step di pi greco decimi

array([-3.14159265, -2.82743339, -2.51327412, -2.19911486, -1.88495559,
       -1.57079633, -1.25663706, -0.9424778 , -0.62831853, -0.31415927,
        0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
        1.57079633,  1.88495559,  2.19911486,  2.51327412,  2.82743339])

In [79]:
np.linspace(-np.pi, np.pi, 100)#gli dico da dove partire a dove arrivare e gli dico quanti punti voglio 
#è L'UNICA FUNZIONE PYTHON IN CUI L'ULTIMO ELEMENTO è INCLUSO, IN QUESTO CASO IL CENTESIMO 

array([-3.14159265, -3.07812614, -3.01465962, -2.9511931 , -2.88772658,
       -2.82426006, -2.76079354, -2.69732703, -2.63386051, -2.57039399,
       -2.50692747, -2.44346095, -2.37999443, -2.31652792, -2.2530614 ,
       -2.18959488, -2.12612836, -2.06266184, -1.99919533, -1.93572881,
       -1.87226229, -1.80879577, -1.74532925, -1.68186273, -1.61839622,
       -1.5549297 , -1.49146318, -1.42799666, -1.36453014, -1.30106362,
       -1.23759711, -1.17413059, -1.11066407, -1.04719755, -0.98373103,
       -0.92026451, -0.856798  , -0.79333148, -0.72986496, -0.66639844,
       -0.60293192, -0.53946541, -0.47599889, -0.41253237, -0.34906585,
       -0.28559933, -0.22213281, -0.1586663 , -0.09519978, -0.03173326,
        0.03173326,  0.09519978,  0.1586663 ,  0.22213281,  0.28559933,
        0.34906585,  0.41253237,  0.47599889,  0.53946541,  0.60293192,
        0.66639844,  0.72986496,  0.79333148,  0.856798  ,  0.92026451,
        0.98373103,  1.04719755,  1.11066407,  1.17413059,  1.23

In [80]:
np.logspace(-3, 3, 7)#i punti sono equidistanziati in una scala logaritmica

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

In [81]:
x=np.arange(1,13)

In [82]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
len(x)

12

In [ ]:
A=x.reshape((3,4))#è importante mettere le doppie parentesi perchè reshape vuole un solo parametro 
#che in questo caso se è una tupla con numero di righe e numero di colonne, quindi bidimensionale
#reshape cambia la forma del vettore

In [85]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
x=np.arange(1, 501)

In [87]:
A=x.reshape((500//25, 25))

In [88]:
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175],
      

In [ ]:
A=x.reshape((-1, 25))#quando nella reshape metto -1, vuol dire metti in quella dimensione tanti elementi quanti te ne servono per finire i numeri
#funziona perchè il vettore x ha un numero di elementi che è un multiplo di 25
#LE FUNZIONI DI RESHAPE FUNZIONA SOLO SE LE DUE FORME HANNO LO STESSO NUMERO DI ELEMENTI

In [90]:
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175],
      

In [91]:
A=x.reshape((10, -1))

In [92]:
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
     

In [97]:
x=np.array([0, 4, -1, 7])

In [98]:
xr=x.reshape ((1, -1))#questo è il modo per avere un vettore riga
xr=x.reshape((1, len(x)))#scrittura equivalente ma non usata

In [99]:
xr

array([[ 0,  4, -1,  7]])

In [101]:
xc=x.reshape ((-1, 1))#questo è il modo per avere un vettore colonna
xc=x.reshape((len(x), 1))#scrittura equivalente ma non usata

In [102]:
xc

array([[ 0],
       [ 4],
       [-1],
       [ 7]])

In [ ]:
#piccole parentesi

In [103]:
import sys #è una libreria di sistema 

In [104]:
x=np.ones(1000)

In [105]:
x.nbytes

8000

In [106]:
sys.getsizeof(x)

8112

In [107]:
l=list(x)

In [ ]:
sys.getsizeof(l)#in toeria la lista è più grande del vettore, qui ci deve essere un errore

8056

In [109]:
A=np.array([[1, 2, 3], [4, 5, 6]])

In [111]:
B=A

In [ ]:
B[0,0]=32 #come con le liste, modifico sia b che a proprio perchè si comportano come puntatori

In [113]:
A

array([[32,  2,  3],
       [ 4,  5,  6]])

In [ ]:
B=A[0,:].copy()#solo in questo modo creo una copia e non modifico A, altrimenti modificherei A

In [ ]:
#ritorniamo all'argomento principale

In [114]:
x=np.ones(10)
y=np.zeros(10)


In [ ]:
np.concatenate((x, y))#il parametro è la tupla di oggetti che vogliamo concatenare, in questo caso sto dicendo di concatenare x e y
#se i vettori sono monodimensionali non ha dubbi è come se facesse un append

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [116]:
x=np.ones(10).reshape((1,-1))
y=np.zeros(10).reshape((1,-1))


In [117]:
np.concatenate((x, y), axis=0)#con vettori multidimensionali, devo specificare con axis l'asse lungo il quale incollare

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [119]:
np.concatenate((x, y), axis=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [122]:
x=np.arange(50).reshape((1, -1))#devo necessariamente rendere x bidimensionale per poterlo concatenare a I

In [123]:
I=np.eye(50)

In [124]:
np.concatenate((x, I), axis=0)

array([[ 0.,  1.,  2., ..., 47., 48., 49.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])